"""add_analysis_records_and_reviews

Revision ID: b8678ebaa440
Revises: 4f38586d77d6
Create Date: 2026-07-24 16:47:03.312976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8678ebaa440'
down_revision: Union[str, None] = '4f38586d77d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('automation_run_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('structured_result', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('overall_risk', sa.String(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_manual_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_time_saved_minutes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_analysis_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['parent_analysis_id'], ['analysis_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_records_analysis_type'), 'analysis_records', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_records_automation_run_id'), 'analysis_records', ['automation_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_records_created_at'), 'analysis_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_records_document_id'), 'analysis_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_analysis_records_status'), 'analysis_records', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_records_user_id'), 'analysis_records', ['user_id'], unique=False)
    op.create_table('analysis_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_record_id', sa.String(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_record_id'], ['analysis_records.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reviews_analysis_record_id'), 'analysis_reviews', ['analysis_record_id'], unique=False)
    op.create_index(op.f('ix_analysis_reviews_created_at'), 'analysis_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_reviews_reviewer_user_id'), 'analysis_reviews', ['reviewer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_reviews_reviewer_user_id'), table_name='analysis_reviews')
    op.drop_index(op.f('ix_analysis_reviews_created_at'), table_name='analysis_reviews')
    op.drop_index(op.f('ix_analysis_reviews_analysis_record_id'), table_name='analysis_reviews')
    op.drop_table('analysis_reviews')
    op.drop_index(op.f('ix_analysis_records_user_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_status'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_document_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_created_at'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_automation_run_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_analysis_type'), table_name='analysis_records')
    op.drop_table('analysis_records')
    # ### end Alembic commands ###
